run:
  go: 1.21
  timeout: 5m
linters:
  enable:
    - gofmt
    - bodyclose
    - staticcheck
    - unused
    - gci
    - gomodguard
    - tenv
    - gosimple
    - govet
  disable:
    - errcheck
    - ineffassign
  #  - structcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/khulnasoft-lab/)
      - blank
      - dot
  gomodguard:
    blocked:
      modules:
        - github.com/hashicorp/go-version:
            recommendations:
              - github.com/khulnasoft-lab/go-version
            reason: "`khulnasoft-lab/go-version` is degisned for our use-cases"
        - github.com/Masterminds/semver:
            recommendations:
              - github.com/khulnasoft-lab/go-version
            reason: "`khulnasoft-lab/go-version` is degisned for our use-cases"

