name: Update vuln-list repo

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update repo vuln-list
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      VULN_LIST_DIR: "vuln-list"

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v5

      - name: Set up Go with cache
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Checkout vuln-list repo
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository_owner }}/vuln-list
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: ${{ env.VULN_LIST_DIR }}

      - name: Configure GitHub user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Build vuln-list-update
        run: go build -o vuln-list-update .

      # Consolidate all update scripts into a matrix for maintainability
      - name: Run vulnerability source updaters
        run: |
          for update_data in \
            "alpine:Alpine Issue Tracker" \
            "alpine-unfixed:Alpine Secshfixes Tracker" \
            "ubuntu:Ubuntu CVE Tracker" \
            # ... and so on
          do
            target="${update_data%%:*}"
            description="${update_data#*:}"
            ./scripts/update.sh "$target" "$description"
          done

      # Uncomment and configure this section for Microsoft Teams notifications on failure
      # - name: Microsoft Teams Notification
      #   if: failure()
      #   uses: Skitionek/notify-microsoft-teams@e7a2493ac87dad8aa7a62f079f295e54ff511d88
      #   with:
      #     webhook_url: ${{ secrets.TRIVY_MSTEAMS_WEBHOOK }}
      #     needs: ${{ toJson(needs) }}
      #     job: ${{ toJson(job) }}
      #     steps: ${{ toJson(steps) }}
