name: Update vuln-list repo

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update repo vuln-list
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
      VULN_LIST_DIR: "vuln-list"

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v5

      - name: Set up Go with cache
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Checkout vuln-list repo
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository_owner }}/vuln-list
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: ${{ env.VULN_LIST_DIR }}

      - name: Configure GitHub user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Build vuln-list-update
        run: go build -o vuln-list-update .

      # Consolidate all update scripts into a matrix for maintainability
      - name: Run vulnerability source updaters
        run: ./scripts/update.sh ${{ matrix.target }} "${{ matrix.description }}"
        if: always()
        strategy:
          fail-fast: false
          matrix:
            include:
              - target: alpine
                description: "Alpine Issue Tracker"
              - target: alpine-unfixed
                description: "Alpine Secshfixes Tracker"
              - target: ubuntu
                description: "Ubuntu CVE Tracker"
              - target: amazon
                description: "Amazon Linux Security Center"
              - target: oracle-oval
                description: "Oracle Linux OVAL"
              - target: photon
                description: "Photon Security Advisories"
              - target: ghsa
                description: "GitHub Security Advisory"
              - target: cwe
                description: "CWE"
              - target: suse-cvrf
                description: "SUSE CVRF"
              - target: glad
                description: "GitLab Advisory Database"
              - target: alma
                description: "AlmaLinux Security Advisory"
              - target: rocky
                description: "Rocky Linux Security Advisory"
              - target: azure
                description: "Azure Linux and CBL-Mariner Vulnerability Data"
              - target: osv
                description: "OSV Database"
              - target: wolfi
                description: "Wolfi Security Data"
              - target: chainguard
                description: "Chainguard Security Data"
              - target: openeuler
                description: "openEuler CVE Data"
              - target: echo
                description: "Echo CVE Data"
              - target: minimos
                description: "MinimOS Security Data"
              - target: seal
                description: "Seal Security Data"
              - target: eoldates
                description: "EOL dates"
              - target: rootio
                description: "Root CVE Feed Tracker"

      # Uncomment and configure this section for Microsoft Teams notifications on failure
      # - name: Microsoft Teams Notification
      #   if: failure()
      #   uses: Skitionek/notify-microsoft-teams@e7a2493ac87dad8aa7a62f079f295e54ff511d88
      #   with:
      #     webhook_url: ${{ secrets.TRIVY_MSTEAMS_WEBHOOK }}
      #     needs: ${{ toJson(needs) }}
      #     job: ${{ toJson(job) }}
      #     steps: ${{ toJson(steps) }}
